// Copyright 2015 The go-net-upnp Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package upnp

const (
	PRODUCT_VERSION = "0.8"
	PRODUCT_NAME    = "go-net-upnp"

	SUPPORT_VERSION       = "1.1"
	SUPPORT_VERSION_MAJOR = 1
	SUPPORT_VERSION_MINOR = 1

	CONTROLPOINT_DEFAULT_PORT_BASE  = 5004
	CONTROLPOINT_DEFAULT_PORT_RANGE = 1024
	CONTROLPOINT_DEFAULT_PORT_MAX   = CONTROLPOINT_DEFAULT_PORT_BASE + CONTROLPOINT_DEFAULT_PORT_RANGE

	DEVICE_DEFAULT_PORT_BASE  = 6004
	DEVICE_DEFAULT_PORT_RANGE = 1024
	DEVICE_DEFAULT_PORT_MAX   = DEVICE_DEFAULT_PORT_BASE + DEVICE_DEFAULT_PORT_RANGE
)
